const PSYCHOACTIVE_PATHWAYS_CLIENT_THEME_VARIANT = 'PSYCHOACTIVE_PATHWAYS_CLIENT_THEME_VARIANT';
const BASE_URL = 'https://simple-smtp.onrender.com';

export const PSYCHOACTIVE_PATHWAYS_CLIENT_CONSTANTS = {PSYCHOACTIVE_PATHWAYS_CLIENT_THEME_VARIANT, BASE_URL};