const PSYCHOACTIVE_PATHWAYS_CLIENT_THEME_VARIANT = 'PSYCHOACTIVE_PATHWAYS_CLIENT_THEME_VARIANT';
const BASE_URL = 'https://psychoactive-pathways-api.onrender.com';
// const BASE_URL = 'http://localhost:8000';

export const PSYCHOACTIVE_PATHWAYS_CLIENT_CONSTANTS = {PSYCHOACTIVE_PATHWAYS_CLIENT_THEME_VARIANT, BASE_URL};